name: Export Secrets

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  export-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Export secrets to env.conf
        run: |
          echo "# Environment variables" > env.conf
          echo "SECRET2=$SECRET2" >> env.conf
        env:
          SECRET2: ${{ secrets.SECRET2 }}

      - name: Show env.conf
        run: cat env.conf

      - name: Commit changes
        run: |
          git config --global user.email "ankit.bakshi@wbdcontractor.com"
          git config --global user.name "Ankit Bakshi"
          git add env.conf
          git commit -m "Updated env.conf"
          git push
